version: 2
run:
  tests: true
linters:
  enable:
    - errcheck
    - unused
    - govet
    - ineffassign
    - staticcheck
    - intrange
    - misspell
    - nilnil
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
